### ISSUE TITLE
不知道能不能同时支持tw和panda

### ISSUE THREAD

**Issue by bingtsingw** [sonofmagic/weapp-pandacss#12]
目前好像加上tw的配置之后, panda就失效了

**Comment by sonofmagic** [comment]
可以的，我写了一个 uni-app 的 demo, 里面就同时使用了 `weapp-pandacss` 和 `weapp-tailwindcss` 同时开发小程序，

详见项目: https://github.com/sonofmagic/weapp-pandacss/tree/main/examples/uni-app-vue3
