### ISSUE TITLE
taro-react-pandacss-template 模板中使用版本是0.13.1，是否支持最新版？

### ISSUE THREAD

**Issue by leifeng** [sonofmagic/weapp-pandacss#66]
按[官方说明](https://github.com/sonofmagic/weapp-pandacss/blob/main/README.md)安装后，样式不生效，如果把pandacss/dev版本改成例子里[0.19.0](https://github.com/sonofmagic/weapp-pandacss/blob/b26d1504d980e134fad0a1e72e1f6f9d87c0cbc8/examples/package.json#L15)和[0.13.1](https://github.com/sonofmagic/taro-react-pandacss-template/blob/9eccf6e7a7b7bfa51349a5c7dfc6e4c7530c2277/package.json#L61)可以正常显示
> npm install -D @pandacss/dev weapp-pandacss postcss # 或者 yarn / pnpm
> npx panda init

**Comment by sonofmagic** [comment]
可能 `pandacss` 新的版本改了一些东西，我没有兼顾到吧, 这个项目用的人非常少，最近也挺久没有更新了。
你是想要在小程序里面用嘛，要不先试试 [`weapp-tailwindcss`](https://weapp-tw.icebreaker.top/) 哈哈哈 LOL

**Comment by sonofmagic** [comment]
已经在 [weapp-pandacss](https://github.com/sonofmagic/weapp-pandacss)@1.5.0 中支持最新的  "@pandacss/dev": "0.39.1" 版本了，
具体可以运行模板 : https://github.com/sonofmagic/taro-react-pandacss-template

**Comment by leifeng** [comment]
好的
